Add support for Cortex-M4 w/o FPU
flit/argon-rtos pull request #17
Opened 2021-12-17 19:06 UTC by patrislav1

I'm testing Argon RTOS on a ATSAM4LS8C, which is a Cortex-M4 without FPU.
When compiling for this chip, gcc assembler refuses to translate the FPU-specific instructions (see below).

I added an alternative `ar_handlers_cm4_nofpu.S` which does the same as `ar_handlers_cm4.S`, but without doing the FPU-specific extended frame handling.

```
/home/patrick/src/argon-rtos/src/cortex_m/ar_handlers_cm4.S: Assembler messages:
/home/patrick/src/argon-rtos/src/cortex_m/ar_handlers_cm4.S:64: Error: selected FPU does not support instruction -- `vstmdb r0!,{s16-s31}'
/home/patrick/src/argon-rtos/src/cortex_m/ar_handlers_cm4.S:90: Error: selected FPU does not support instruction -- `vldmia r0!,{s16-s31}'
```

2021-12-17 21:36 UTC, flit requested changes
Just the copyright.

2021-12-17 21:36 UTC, flit commented on src/cortex_m/ar_handlers_cm4_nofpu.S
> + *
Please insert your copyright here.

2021-12-17 21:37 UTC, flit commented
Thanks!

2021-12-18 10:52 UTC, patrislav1 commented on src/cortex_m/ar_handlers_cm4_nofpu.S
> + *
Added (c) as suggested.

2021-12-18 20:13 UTC, flit approved these changes

2021-12-18 20:14 UTC, merged